version: '2.1'
services:
    redis:
        image: 'redis:5.0.5-alpine'
        # command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # Lines to persist data on the local filesystem.
        #    - PGDATA=/var/lib/postgresql/data/pgdata
        #volumes:
        #    - ./pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        image: docker-airflow-enhanced
        build:
            context: ./
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - EXECUTOR=Celery
        env_file:
            - ./env_file.env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./requirements.txt:/requirements.txt
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: docker-airflow-enhanced
        build:
            context: ./
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        env_file:
            - ./env_file.env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./requirements.txt:/requirements.txt
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: docker-airflow-enhanced
        build:
            context: ./
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./requirements.txt:/requirements.txt
        environment:
            - EXECUTOR=Celery
        env_file:
            - ./env_file.env
        command: scheduler

    worker:
        image: docker-airflow-enhanced
        build:
            context: ./
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./requirements.txt:/requirements.txt
        environment:
            - EXECUTOR=Celery
        env_file:
            - ./env_file.env
        command: worker